/*
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS covers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
*/

CREATE TABLE IF NOT EXISTS covers(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS books(
	id BIGSERIAL PRIMARY KEY,
	isbn CHAR(17) UNIQUE NOT NULL,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	pages INTEGER,
	cover_id BIGINT REFERENCES covers,
	price DECIMAL(10, 2) DEFAULT 0.0 NOT NULL,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE roles (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	lastName VARCHAR (50) NOT NULL,
	role_id BIGINT REFERENCES roles,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	birthday DATE,
	deleted BOOLEAN DEFAULT false NOT NULL
);