/*
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS orderItems;
*/

CREATE TABLE IF NOT EXISTS books(
	id BIGSERIAL PRIMARY KEY,
	isbn CHAR(17) UNIQUE NOT NULL,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	pages INTEGER,
	cover_id BIGINT,
	price DECIMAL(10, 2) DEFAULT 0.0 NOT NULL,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	lastName VARCHAR (50) NOT NULL,
	role_id BIGINT,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	birthday DATE,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_cost DECIMAL NOT NULL,
    timestamp TIMESTAMP DEFAULT current_timestamp,
    status_id BIGINT REFERENCES status
);

CREATE TABLE IF NOT EXISTS orderItems(
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders,
    book_id BIGINT REFERENCES books NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL NOT NULL
);